# Generated by Django 4.1.6 on 2023-02-02 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dirigeant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30, unique=True)),
                ('prenom', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Magasin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('adresse', models.CharField(max_length=50)),
                ('ca', models.FloatField()),
                ('dirigeant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appGestion.dirigeant')),
            ],
        ),
        migrations.CreateModel(
            name='Meuble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('etat', models.CharField(choices=[('NF', 'NEUF'), ('OC', 'OCCASION'), ('ME', 'MAUVAIS ETAT'), ('INU', 'INUTILSABLE')], max_length=3)),
                ('prix', models.FloatField()),
                ('statut', models.CharField(choices=[('LBR', 'LIBRE'), ('VDU', 'VENDU')], max_length=30)),
                ('lieu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appGestion.magasin')),
            ],
        ),
    ]
